// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Plane_Crash_Visualization.Data;

#nullable disable

namespace Plane_Crash_Visualization.Migrations
{
    [DbContext(typeof(CrashDbContext))]
    [Migration("20250630221529_AddPassengerCrewColumnsDetailed")]
    partial class AddPassengerCrewColumnsDetailed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Plane_Crash_Visualization.Models.Crash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AC_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Aboard")
                        .HasColumnType("int");

                    b.Property<int?>("AboardCrew")
                        .HasColumnType("int");

                    b.Property<int?>("AboardPassengers")
                        .HasColumnType("int");

                    b.Property<string>("Cn_ln")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Fatalities")
                        .HasColumnType("int");

                    b.Property<int?>("FatalitiesCrew")
                        .HasColumnType("int");

                    b.Property<int?>("FatalitiesPassengers")
                        .HasColumnType("int");

                    b.Property<string>("Flight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ground")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Time")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Crashes");
                });
#pragma warning restore 612, 618
        }
    }
}
